definitions:
  api.errorResponse:
    properties:
      error:
        type: string
    type: object
  game.Game:
    properties:
      active_player:
        type: string
      drawn_players:
        items:
          type: string
        type: array
      id:
        type: string
      losing_players:
        items:
          type: string
        type: array
      state:
        $ref: '#/definitions/game.gameState'
      winning_players:
        items:
          type: string
        type: array
    type: object
  game.RequestConcedeGame:
    properties:
      player_id:
        type: string
    type: object
  game.gameState:
    enum:
    - not_started
    - started
    - finished
    type: string
    x-enum-varnames:
    - StateNotStarted
    - StateStarted
    - StateFinished
  player.Player:
    properties:
      display_name:
        type: string
      id:
        type: string
    type: object
  player.RequestNewPlayer:
    properties:
      display_name:
        type: string
    type: object
  room.RequestJoinRoom:
    properties:
      player_id:
        type: string
    type: object
  room.RequestLeaveRoom:
    properties:
      player_id:
        type: string
    type: object
  room.RequestNewRoom:
    properties:
      room_name:
        type: string
    type: object
  room.RequestStartGame:
    properties:
      player_time_ms:
        type: integer
      room_id:
        type: string
    type: object
  room.Room:
    properties:
      game_id:
        type: string
      id:
        type: string
      name:
        type: string
      players:
        items:
          type: string
        type: array
    type: object
info:
  contact: {}
paths:
  /api/game:
    post:
      consumes:
      - application/json
      parameters:
      - description: request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/room.RequestStartGame'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/game.Game'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.errorResponse'
      summary: Start a game.
  /api/game/{game_id}/concede:
    post:
      consumes:
      - application/json
      parameters:
      - description: room id
        in: path
        name: game_id
        required: true
        type: string
      - description: request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/game.RequestConcedeGame'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/game.Game'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.errorResponse'
      summary: Player concedes a game.
  /api/player:
    post:
      consumes:
      - application/json
      parameters:
      - description: request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/player.RequestNewPlayer'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/player.Player'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.errorResponse'
      summary: Create a new player.
  /api/player/{player_id}:
    get:
      parameters:
      - description: player id
        in: path
        name: player_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/player.Player'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.errorResponse'
      summary: Get player by id.
  /api/room:
    post:
      consumes:
      - application/json
      parameters:
      - description: request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/room.RequestNewRoom'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/room.Room'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.errorResponse'
      summary: Create a new room.
  /api/room/{room_id}:
    get:
      parameters:
      - description: room id
        in: path
        name: room_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/room.Room'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.errorResponse'
      summary: Get room by id.
  /api/room/{room_id}/join:
    post:
      consumes:
      - application/json
      parameters:
      - description: room id
        in: path
        name: room_id
        required: true
        type: string
      - description: request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/room.RequestJoinRoom'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/room.Room'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.errorResponse'
      summary: Add player to a room.
  /api/room/{room_id}/leave:
    post:
      consumes:
      - application/json
      parameters:
      - description: room id
        in: path
        name: room_id
        required: true
        type: string
      - description: request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/room.RequestLeaveRoom'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/room.Room'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.errorResponse'
      summary: Remove player from a room.
  /api/rooms:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/room.Room'
            type: array
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.errorResponse'
      summary: Get all rooms.
swagger: "2.0"
