name: Container CI/CD
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Build Image
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t server:$IMAGE_TAG server/.
